# -*- coding: utf-8 -*-
"""Matplotlib_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yutRoRggWew5Rz9wbX2f_OFbY-GNnkZs
"""

import pandas as pd
import matplotlib.pyplot as plt

"""Vamos a ver cómo poner dos series de datos en la misma gráfica. Primero creamos un DataFrame con dos columnas, las coordenadas x e y de algunos puntos de la recta y = 2 * x + 3"""

recta_x = pd.Series([x for x in range(10)])
recta_y = recta_x * 2 + 3
recta = pd.concat([recta_x, recta_y], axis = 1)
recta.columns = ['eje_x', 'eje_y']
recta.head()

"""
Otro para representar y = x²

"""

para_x = pd.Series([x for x in range(-5, 6)])
para_y = para_x.pow(2)
para = pd.concat([para_x, para_y], axis = 1)
para.columns = ['eje_x', 'eje_y']
para.head()

"""Ahora creamos la figura. Para representar más de una serie en un solo Axes, simplemente  hay que llamar varias a la función correspondiente, en este caso plot"""

fig, ax = plt.subplots()
ax.plot('eje_x', 'eje_y', data = recta, label = "Recta")
ax.plot('eje_x', 'eje_y', data = para, label = "Parábola")
ax.legend()
plt.show()

"""Para centrar los ejes como se suele hacer en matemáticas"""

fig, ax = plt.subplots()
ax.plot('eje_x', 'eje_y', data = recta, label = "Recta")
ax.plot('eje_x', 'eje_y', data = para, label = "Parábola")
# centrar los ejes
ax.spines['left'].set_position(('data', 0.0))
ax.spines['bottom'].set_position(('data', 0.0))
ax.spines['right'].set_color('none')
ax.spines['top'].set_color('none')

ax.legend()
plt.show()

"""Ahora veamos cómo hacer una figura con dos subplots, uno encima del otro. Es decir, 2 filas y 1 columna."""

# los argumentos indican que habrá dos filas y una columna de subplots
fig, ax = plt.subplots(nrows = 2, ncols = 1)
fig.suptitle("Figure con dos subplots")
ax[0].plot('eje_x', 'eje_y', data = recta, label = "Recta")
ax[1].plot('eje_x', 'eje_y', data = para, label = "Parábola")
ax[0].legend()
ax[1].legend()
plt.show()

"""Lo mismo pero con dos filas y dos columnas. Hay que usar dos índices para elegir el Axes."""

# los argumentos indican que habrá dos filas y una columna de subplots
fig, ax = plt.subplots(nrows = 2, ncols = 2)
fig.suptitle("Figure con cuatro subplots")
ax[0, 0].plot('eje_x', 'eje_y', data = recta, label = "Recta")
ax[1, 0].plot('eje_x', 'eje_y', data = para, label = "Parábola")
ax[0, 1].plot('eje_x', 'eje_y', data = recta, label = "Recta2")
ax[1, 1].plot('eje_x', 'eje_y', data = para, label = "Parábola2")
ax[0, 0].legend()
ax[0, 1].legend()
ax[1, 0].legend()
ax[1, 1].legend()
plt.show()

